import "./globals.css";
import { Inter } from "next/font/google";
import RootClient from "./rootClient";
import Header from "../components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  
  return (
    <html lang="en">
      <body className="h-screen w-screen">
        <RootClient>{children}</RootClient>
      </body>
    </html>
  );
}
